"""mouneh production module: raw materials, products, recipes, batches, finished goods, sales

Revision ID: 90a7c8cee8bc
Revises: 9bcd61fb309c
Create Date: 2026-08-28 09:06:31.251340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90a7c8cee8bc'
down_revision: Union[str, None] = '9bcd61fb309c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_RLS_TABLES = [
    "raw_material",
    "mouneh_product",
    "mouneh_recipe",
    "mouneh_recipe_item",
    "mouneh_cost_component",
    "mouneh_production_batch",
    "mouneh_batch_input_consumption",
    "mouneh_finished_goods_stock",
    "mouneh_sale",
]


def _enable_rls(table: str) -> None:
    # Mandatory tenant isolation for every new farm-data-plane table — see
    # TENANCY.md and the initial tenant migration, which created
    # app_current_tenant_id().
    op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
    op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
    op.execute(
        f"""
        CREATE POLICY tenant_isolation_{table}
        ON {table}
        USING (tenant_id = app_current_tenant_id())
        WITH CHECK (tenant_id = app_current_tenant_id())
        """
    )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mouneh_batch_input_consumption',
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.String(length=64), nullable=False),
    sa.Column('planned_qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('actual_qty', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('origin_device_id', sa.UUID(), nullable=True),
    sa.Column('last_modified_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mouneh_batch_input_consumption_batch_id'), 'mouneh_batch_input_consumption', ['batch_id'], unique=False)
    op.create_index(op.f('ix_mouneh_batch_input_consumption_farm_id'), 'mouneh_batch_input_consumption', ['farm_id'], unique=False)
    op.create_index(op.f('ix_mouneh_batch_input_consumption_tenant_id'), 'mouneh_batch_input_consumption', ['tenant_id'], unique=False)
    op.create_table('mouneh_cost_component',
    sa.Column('recipe_id', sa.UUID(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('cost_type', sa.String(length=32), nullable=False),
    sa.Column('calculation_method', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('allocation_basis', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('origin_device_id', sa.UUID(), nullable=True),
    sa.Column('last_modified_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mouneh_cost_component_batch_id'), 'mouneh_cost_component', ['batch_id'], unique=False)
    op.create_index(op.f('ix_mouneh_cost_component_farm_id'), 'mouneh_cost_component', ['farm_id'], unique=False)
    op.create_index(op.f('ix_mouneh_cost_component_recipe_id'), 'mouneh_cost_component', ['recipe_id'], unique=False)
    op.create_index(op.f('ix_mouneh_cost_component_tenant_id'), 'mouneh_cost_component', ['tenant_id'], unique=False)
    op.create_table('mouneh_finished_goods_stock',
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity_produced', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('quantity_available', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('quantity_reserved', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('quantity_sold', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('quantity_damaged', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('quantity_expired', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('warehouse_location', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('origin_device_id', sa.UUID(), nullable=True),
    sa.Column('last_modified_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mouneh_finished_goods_stock_batch_id'), 'mouneh_finished_goods_stock', ['batch_id'], unique=False)
    op.create_index(op.f('ix_mouneh_finished_goods_stock_farm_id'), 'mouneh_finished_goods_stock', ['farm_id'], unique=False)
    op.create_index(op.f('ix_mouneh_finished_goods_stock_product_id'), 'mouneh_finished_goods_stock', ['product_id'], unique=False)
    op.create_index(op.f('ix_mouneh_finished_goods_stock_tenant_id'), 'mouneh_finished_goods_stock', ['tenant_id'], unique=False)
    op.create_table('mouneh_product',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('photo_path', sa.String(), nullable=True),
    sa.Column('output_unit', sa.String(length=32), nullable=False),
    sa.Column('custom_output_unit_label', sa.String(), nullable=True),
    sa.Column('default_batch_size', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('shelf_life_days', sa.Integer(), nullable=True),
    sa.Column('warehouse_rules', sa.String(), nullable=True),
    sa.Column('low_stock_threshold', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('target_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('wholesale_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('target_margin_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('origin_device_id', sa.UUID(), nullable=True),
    sa.Column('last_modified_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mouneh_product_farm_id'), 'mouneh_product', ['farm_id'], unique=False)
    op.create_index(op.f('ix_mouneh_product_tenant_id'), 'mouneh_product', ['tenant_id'], unique=False)
    op.create_table('mouneh_production_batch',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('recipe_version_id', sa.UUID(), nullable=False),
    sa.Column('batch_code', sa.String(length=64), nullable=False),
    sa.Column('planned_qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('actual_output_qty', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('waste_qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('damaged_qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('quality_status', sa.String(length=32), nullable=False),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('warehouse_location', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('planned_unit_cost', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('planned_total_cost', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('actual_unit_cost', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('actual_total_cost', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('labor_hours', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('origin_device_id', sa.UUID(), nullable=True),
    sa.Column('last_modified_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mouneh_production_batch_farm_id'), 'mouneh_production_batch', ['farm_id'], unique=False)
    op.create_index(op.f('ix_mouneh_production_batch_product_id'), 'mouneh_production_batch', ['product_id'], unique=False)
    op.create_index(op.f('ix_mouneh_production_batch_tenant_id'), 'mouneh_production_batch', ['tenant_id'], unique=False)
    op.create_table('mouneh_recipe',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('basis_quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('basis_unit', sa.String(length=32), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('origin_device_id', sa.UUID(), nullable=True),
    sa.Column('last_modified_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mouneh_recipe_farm_id'), 'mouneh_recipe', ['farm_id'], unique=False)
    op.create_index(op.f('ix_mouneh_recipe_product_id'), 'mouneh_recipe', ['product_id'], unique=False)
    op.create_index(op.f('ix_mouneh_recipe_tenant_id'), 'mouneh_recipe', ['tenant_id'], unique=False)
    op.create_table('mouneh_recipe_item',
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.String(length=64), nullable=False),
    sa.Column('material_type', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('loss_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_optional', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('origin_device_id', sa.UUID(), nullable=True),
    sa.Column('last_modified_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mouneh_recipe_item_farm_id'), 'mouneh_recipe_item', ['farm_id'], unique=False)
    op.create_index(op.f('ix_mouneh_recipe_item_recipe_id'), 'mouneh_recipe_item', ['recipe_id'], unique=False)
    op.create_index(op.f('ix_mouneh_recipe_item_tenant_id'), 'mouneh_recipe_item', ['tenant_id'], unique=False)
    op.create_table('mouneh_sale',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('finished_goods_stock_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('cost_per_unit', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('margin', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sold_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('origin_device_id', sa.UUID(), nullable=True),
    sa.Column('last_modified_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mouneh_sale_farm_id'), 'mouneh_sale', ['farm_id'], unique=False)
    op.create_index(op.f('ix_mouneh_sale_product_id'), 'mouneh_sale', ['product_id'], unique=False)
    op.create_index(op.f('ix_mouneh_sale_tenant_id'), 'mouneh_sale', ['tenant_id'], unique=False)
    op.create_table('raw_material',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('inventory_item_id', sa.UUID(), nullable=True),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('default_unit_cost', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('stock_tracking_enabled', sa.Boolean(), nullable=False),
    sa.Column('current_stock', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('loss_percent_default', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('origin_device_id', sa.UUID(), nullable=True),
    sa.Column('last_modified_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_material_farm_id'), 'raw_material', ['farm_id'], unique=False)
    op.create_index(op.f('ix_raw_material_tenant_id'), 'raw_material', ['tenant_id'], unique=False)
    for _table in _RLS_TABLES:
        _enable_rls(_table)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_material_tenant_id'), table_name='raw_material')
    op.drop_index(op.f('ix_raw_material_farm_id'), table_name='raw_material')
    op.drop_table('raw_material')
    op.drop_index(op.f('ix_mouneh_sale_tenant_id'), table_name='mouneh_sale')
    op.drop_index(op.f('ix_mouneh_sale_product_id'), table_name='mouneh_sale')
    op.drop_index(op.f('ix_mouneh_sale_farm_id'), table_name='mouneh_sale')
    op.drop_table('mouneh_sale')
    op.drop_index(op.f('ix_mouneh_recipe_item_tenant_id'), table_name='mouneh_recipe_item')
    op.drop_index(op.f('ix_mouneh_recipe_item_recipe_id'), table_name='mouneh_recipe_item')
    op.drop_index(op.f('ix_mouneh_recipe_item_farm_id'), table_name='mouneh_recipe_item')
    op.drop_table('mouneh_recipe_item')
    op.drop_index(op.f('ix_mouneh_recipe_tenant_id'), table_name='mouneh_recipe')
    op.drop_index(op.f('ix_mouneh_recipe_product_id'), table_name='mouneh_recipe')
    op.drop_index(op.f('ix_mouneh_recipe_farm_id'), table_name='mouneh_recipe')
    op.drop_table('mouneh_recipe')
    op.drop_index(op.f('ix_mouneh_production_batch_tenant_id'), table_name='mouneh_production_batch')
    op.drop_index(op.f('ix_mouneh_production_batch_product_id'), table_name='mouneh_production_batch')
    op.drop_index(op.f('ix_mouneh_production_batch_farm_id'), table_name='mouneh_production_batch')
    op.drop_table('mouneh_production_batch')
    op.drop_index(op.f('ix_mouneh_product_tenant_id'), table_name='mouneh_product')
    op.drop_index(op.f('ix_mouneh_product_farm_id'), table_name='mouneh_product')
    op.drop_table('mouneh_product')
    op.drop_index(op.f('ix_mouneh_finished_goods_stock_tenant_id'), table_name='mouneh_finished_goods_stock')
    op.drop_index(op.f('ix_mouneh_finished_goods_stock_product_id'), table_name='mouneh_finished_goods_stock')
    op.drop_index(op.f('ix_mouneh_finished_goods_stock_farm_id'), table_name='mouneh_finished_goods_stock')
    op.drop_index(op.f('ix_mouneh_finished_goods_stock_batch_id'), table_name='mouneh_finished_goods_stock')
    op.drop_table('mouneh_finished_goods_stock')
    op.drop_index(op.f('ix_mouneh_cost_component_tenant_id'), table_name='mouneh_cost_component')
    op.drop_index(op.f('ix_mouneh_cost_component_recipe_id'), table_name='mouneh_cost_component')
    op.drop_index(op.f('ix_mouneh_cost_component_farm_id'), table_name='mouneh_cost_component')
    op.drop_index(op.f('ix_mouneh_cost_component_batch_id'), table_name='mouneh_cost_component')
    op.drop_table('mouneh_cost_component')
    op.drop_index(op.f('ix_mouneh_batch_input_consumption_tenant_id'), table_name='mouneh_batch_input_consumption')
    op.drop_index(op.f('ix_mouneh_batch_input_consumption_farm_id'), table_name='mouneh_batch_input_consumption')
    op.drop_index(op.f('ix_mouneh_batch_input_consumption_batch_id'), table_name='mouneh_batch_input_consumption')
    op.drop_table('mouneh_batch_input_consumption')
    # ### end Alembic commands ###
