"""farm visits module: activities, packages, visitors, sessions, bookings, ops

Revision ID: cbd6ac9cefaf
Revises: 90a7c8cee8bc
Create Date: 2026-08-28 10:55:08.540054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cbd6ac9cefaf'
down_revision: Union[str, None] = '90a7c8cee8bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_RLS_TABLES = [
    "visit_activity",
    "visit_package",
    "visitor_profile",
    "visit_session",
    "visit_booking",
    "visit_booking_activity",
    "visit_cost",
    "visit_incident",
    "visit_staff_roster",
    "visitor_feedback",
    "visit_retail_sale",
    "visit_opening_calendar_day",
]


def _enable_rls(table: str) -> None:
    # Mandatory tenant isolation for every new farm-data-plane table — see
    # TENANCY.md and the initial tenant migration, which created
    # app_current_tenant_id().
    op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
    op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
    op.execute(
        f"""
        CREATE POLICY tenant_isolation_{table}
        ON {table}
        USING (tenant_id = app_current_tenant_id())
        WITH CHECK (tenant_id = app_current_tenant_id())
        """
    )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visit_activity',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('activity_type', sa.String(length=32), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('capacity_per_slot', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('requires_staff_role', sa.String(), nullable=True),
    sa.Column('requires_animal_id', sa.String(), nullable=True),
    sa.Column('welfare_limit_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('origin_device_id', sa.UUID(), nullable=True),
    sa.Column('last_modified_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visit_activity_farm_id'), 'visit_activity', ['farm_id'], unique=False)
    op.create_index(op.f('ix_visit_activity_tenant_id'), 'visit_activity', ['tenant_id'], unique=False)
    op.create_table('visit_booking',
    sa.Column('visitor_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('adults', sa.Integer(), nullable=False),
    sa.Column('children', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('deposit_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('balance_due', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('origin_device_id', sa.UUID(), nullable=True),
    sa.Column('last_modified_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visit_booking_farm_id'), 'visit_booking', ['farm_id'], unique=False)
    op.create_index(op.f('ix_visit_booking_idempotency_key'), 'visit_booking', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_visit_booking_package_id'), 'visit_booking', ['package_id'], unique=False)
    op.create_index(op.f('ix_visit_booking_session_id'), 'visit_booking', ['session_id'], unique=False)
    op.create_index(op.f('ix_visit_booking_tenant_id'), 'visit_booking', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_visit_booking_visitor_id'), 'visit_booking', ['visitor_id'], unique=False)
    op.create_table('visit_booking_activity',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('origin_device_id', sa.UUID(), nullable=True),
    sa.Column('last_modified_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visit_booking_activity_booking_id'), 'visit_booking_activity', ['booking_id'], unique=False)
    op.create_index(op.f('ix_visit_booking_activity_farm_id'), 'visit_booking_activity', ['farm_id'], unique=False)
    op.create_index(op.f('ix_visit_booking_activity_tenant_id'), 'visit_booking_activity', ['tenant_id'], unique=False)
    op.create_table('visit_cost',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('allocation_method', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('origin_device_id', sa.UUID(), nullable=True),
    sa.Column('last_modified_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visit_cost_farm_id'), 'visit_cost', ['farm_id'], unique=False)
    op.create_index(op.f('ix_visit_cost_session_id'), 'visit_cost', ['session_id'], unique=False)
    op.create_index(op.f('ix_visit_cost_tenant_id'), 'visit_cost', ['tenant_id'], unique=False)
    op.create_table('visit_incident',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('incident_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('action_taken', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('origin_device_id', sa.UUID(), nullable=True),
    sa.Column('last_modified_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visit_incident_farm_id'), 'visit_incident', ['farm_id'], unique=False)
    op.create_index(op.f('ix_visit_incident_session_id'), 'visit_incident', ['session_id'], unique=False)
    op.create_index(op.f('ix_visit_incident_tenant_id'), 'visit_incident', ['tenant_id'], unique=False)
    op.create_table('visit_opening_calendar_day',
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('open_time', sa.String(), nullable=True),
    sa.Column('close_time', sa.String(), nullable=True),
    sa.Column('default_capacity', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('origin_device_id', sa.UUID(), nullable=True),
    sa.Column('last_modified_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visit_opening_calendar_day_farm_id'), 'visit_opening_calendar_day', ['farm_id'], unique=False)
    op.create_index(op.f('ix_visit_opening_calendar_day_tenant_id'), 'visit_opening_calendar_day', ['tenant_id'], unique=False)
    op.create_table('visit_package',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('included_items_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('origin_device_id', sa.UUID(), nullable=True),
    sa.Column('last_modified_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visit_package_farm_id'), 'visit_package', ['farm_id'], unique=False)
    op.create_index(op.f('ix_visit_package_tenant_id'), 'visit_package', ['tenant_id'], unique=False)
    op.create_table('visit_retail_sale',
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('visitor_id', sa.UUID(), nullable=True),
    sa.Column('sale_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('origin_device_id', sa.UUID(), nullable=True),
    sa.Column('last_modified_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visit_retail_sale_farm_id'), 'visit_retail_sale', ['farm_id'], unique=False)
    op.create_index(op.f('ix_visit_retail_sale_tenant_id'), 'visit_retail_sale', ['tenant_id'], unique=False)
    op.create_table('visit_session',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.String(length=8), nullable=False),
    sa.Column('end_time', sa.String(length=8), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('weather_note', sa.String(), nullable=True),
    sa.Column('expected_staff_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('origin_device_id', sa.UUID(), nullable=True),
    sa.Column('last_modified_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visit_session_farm_id'), 'visit_session', ['farm_id'], unique=False)
    op.create_index(op.f('ix_visit_session_tenant_id'), 'visit_session', ['tenant_id'], unique=False)
    op.create_table('visit_staff_roster',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('worker_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('start_time', sa.String(length=8), nullable=False),
    sa.Column('end_time', sa.String(length=8), nullable=False),
    sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('origin_device_id', sa.UUID(), nullable=True),
    sa.Column('last_modified_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visit_staff_roster_farm_id'), 'visit_staff_roster', ['farm_id'], unique=False)
    op.create_index(op.f('ix_visit_staff_roster_session_id'), 'visit_staff_roster', ['session_id'], unique=False)
    op.create_index(op.f('ix_visit_staff_roster_tenant_id'), 'visit_staff_roster', ['tenant_id'], unique=False)
    op.create_table('visitor_feedback',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('would_return', sa.Boolean(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('origin_device_id', sa.UUID(), nullable=True),
    sa.Column('last_modified_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visitor_feedback_booking_id'), 'visitor_feedback', ['booking_id'], unique=False)
    op.create_index(op.f('ix_visitor_feedback_farm_id'), 'visitor_feedback', ['farm_id'], unique=False)
    op.create_index(op.f('ix_visitor_feedback_tenant_id'), 'visitor_feedback', ['tenant_id'], unique=False)
    op.create_table('visitor_profile',
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('preferred_language', sa.String(length=8), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('consent_marketing', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('origin_device_id', sa.UUID(), nullable=True),
    sa.Column('last_modified_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visitor_profile_farm_id'), 'visitor_profile', ['farm_id'], unique=False)
    op.create_index(op.f('ix_visitor_profile_tenant_id'), 'visitor_profile', ['tenant_id'], unique=False)
    for _table in _RLS_TABLES:
        _enable_rls(_table)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visitor_profile_tenant_id'), table_name='visitor_profile')
    op.drop_index(op.f('ix_visitor_profile_farm_id'), table_name='visitor_profile')
    op.drop_table('visitor_profile')
    op.drop_index(op.f('ix_visitor_feedback_tenant_id'), table_name='visitor_feedback')
    op.drop_index(op.f('ix_visitor_feedback_farm_id'), table_name='visitor_feedback')
    op.drop_index(op.f('ix_visitor_feedback_booking_id'), table_name='visitor_feedback')
    op.drop_table('visitor_feedback')
    op.drop_index(op.f('ix_visit_staff_roster_tenant_id'), table_name='visit_staff_roster')
    op.drop_index(op.f('ix_visit_staff_roster_session_id'), table_name='visit_staff_roster')
    op.drop_index(op.f('ix_visit_staff_roster_farm_id'), table_name='visit_staff_roster')
    op.drop_table('visit_staff_roster')
    op.drop_index(op.f('ix_visit_session_tenant_id'), table_name='visit_session')
    op.drop_index(op.f('ix_visit_session_farm_id'), table_name='visit_session')
    op.drop_table('visit_session')
    op.drop_index(op.f('ix_visit_retail_sale_tenant_id'), table_name='visit_retail_sale')
    op.drop_index(op.f('ix_visit_retail_sale_farm_id'), table_name='visit_retail_sale')
    op.drop_table('visit_retail_sale')
    op.drop_index(op.f('ix_visit_package_tenant_id'), table_name='visit_package')
    op.drop_index(op.f('ix_visit_package_farm_id'), table_name='visit_package')
    op.drop_table('visit_package')
    op.drop_index(op.f('ix_visit_opening_calendar_day_tenant_id'), table_name='visit_opening_calendar_day')
    op.drop_index(op.f('ix_visit_opening_calendar_day_farm_id'), table_name='visit_opening_calendar_day')
    op.drop_table('visit_opening_calendar_day')
    op.drop_index(op.f('ix_visit_incident_tenant_id'), table_name='visit_incident')
    op.drop_index(op.f('ix_visit_incident_session_id'), table_name='visit_incident')
    op.drop_index(op.f('ix_visit_incident_farm_id'), table_name='visit_incident')
    op.drop_table('visit_incident')
    op.drop_index(op.f('ix_visit_cost_tenant_id'), table_name='visit_cost')
    op.drop_index(op.f('ix_visit_cost_session_id'), table_name='visit_cost')
    op.drop_index(op.f('ix_visit_cost_farm_id'), table_name='visit_cost')
    op.drop_table('visit_cost')
    op.drop_index(op.f('ix_visit_booking_activity_tenant_id'), table_name='visit_booking_activity')
    op.drop_index(op.f('ix_visit_booking_activity_farm_id'), table_name='visit_booking_activity')
    op.drop_index(op.f('ix_visit_booking_activity_booking_id'), table_name='visit_booking_activity')
    op.drop_table('visit_booking_activity')
    op.drop_index(op.f('ix_visit_booking_visitor_id'), table_name='visit_booking')
    op.drop_index(op.f('ix_visit_booking_tenant_id'), table_name='visit_booking')
    op.drop_index(op.f('ix_visit_booking_session_id'), table_name='visit_booking')
    op.drop_index(op.f('ix_visit_booking_package_id'), table_name='visit_booking')
    op.drop_index(op.f('ix_visit_booking_idempotency_key'), table_name='visit_booking')
    op.drop_index(op.f('ix_visit_booking_farm_id'), table_name='visit_booking')
    op.drop_table('visit_booking')
    op.drop_index(op.f('ix_visit_activity_tenant_id'), table_name='visit_activity')
    op.drop_index(op.f('ix_visit_activity_farm_id'), table_name='visit_activity')
    op.drop_table('visit_activity')
    # ### end Alembic commands ###
