"""initial tenant schema

Revision ID: cebaa357eecc
Revises: 
Create Date: 2026-08-27 17:29:58.869933

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cebaa357eecc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal',
    sa.Column('tag_code', sa.String(length=64), nullable=False),
    sa.Column('species', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('birth_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('origin_device_id', sa.UUID(), nullable=True),
    sa.Column('last_modified_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_animal_farm_id'), 'animal', ['farm_id'], unique=False)
    op.create_index(op.f('ix_animal_tenant_id'), 'animal', ['tenant_id'], unique=False)
    op.create_table('field',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('crop', sa.String(), nullable=True),
    sa.Column('area_hectares', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('origin_device_id', sa.UUID(), nullable=True),
    sa.Column('last_modified_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_farm_id'), 'field', ['farm_id'], unique=False)
    op.create_index(op.f('ix_field_tenant_id'), 'field', ['tenant_id'], unique=False)
    op.create_table('inventory_item',
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('quantity_on_hand', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('origin_device_id', sa.UUID(), nullable=True),
    sa.Column('last_modified_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_item_farm_id'), 'inventory_item', ['farm_id'], unique=False)
    op.create_index(op.f('ix_inventory_item_tenant_id'), 'inventory_item', ['tenant_id'], unique=False)
    op.create_table('inventory_movement',
    sa.Column('inventory_item_id', sa.UUID(), nullable=False),
    sa.Column('quantity_delta', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('origin_device_id', sa.UUID(), nullable=True),
    sa.Column('last_modified_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_movement_farm_id'), 'inventory_movement', ['farm_id'], unique=False)
    op.create_index(op.f('ix_inventory_movement_inventory_item_id'), 'inventory_movement', ['inventory_item_id'], unique=False)
    op.create_index(op.f('ix_inventory_movement_tenant_id'), 'inventory_movement', ['tenant_id'], unique=False)
    op.create_table('sync_event',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('operation', sa.Enum('CREATE', 'UPDATE', 'DELETE', name='syncoperation', native_enum=False, length=64), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_event_device_id'), 'sync_event', ['device_id'], unique=False)
    op.create_index(op.f('ix_sync_event_tenant_id'), 'sync_event', ['tenant_id'], unique=False)
    op.create_table('task',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('origin_device_id', sa.UUID(), nullable=True),
    sa.Column('last_modified_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_farm_id'), 'task', ['farm_id'], unique=False)
    op.create_index(op.f('ix_task_tenant_id'), 'task', ['tenant_id'], unique=False)
    # ### end Alembic commands ###

    # --- Row-Level Security ---------------------------------------------
    # Mandatory tenant isolation boundary for every farm-data-plane table.
    # A SQL boolean expression cannot safely short-circuit an ::uuid cast
    # — Postgres does not guarantee left-to-right evaluation order inside
    # AND — so the policy routes the cast through a STABLE function with
    # an exception handler: it always returns either a valid uuid or NULL,
    # and "tenant_id = NULL" is simply false (zero rows visible/writable)
    # with no risk of a raised error for a connection that bypasses
    # TenantDataRouter and never sets app.tenant_id. FORCE ROW LEVEL
    # SECURITY additionally applies the policy to the table owner. See
    # TENANCY.md.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION app_current_tenant_id() RETURNS uuid
        LANGUAGE plpgsql STABLE AS $fn$
        DECLARE
            raw text;
        BEGIN
            raw := nullif(current_setting('app.tenant_id', true), '');
            IF raw IS NULL THEN
                RETURN NULL;
            END IF;
            RETURN raw::uuid;
        EXCEPTION WHEN invalid_text_representation THEN
            RETURN NULL;
        END;
        $fn$
        """
    )

    tenant_scoped_tables = [
        "animal",
        "field",
        "inventory_item",
        "inventory_movement",
        "sync_event",
        "task",
    ]
    for table in tenant_scoped_tables:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY tenant_isolation_{table}
            ON {table}
            USING (tenant_id = app_current_tenant_id())
            WITH CHECK (tenant_id = app_current_tenant_id())
            """
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_tenant_id'), table_name='task')
    op.drop_index(op.f('ix_task_farm_id'), table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_sync_event_tenant_id'), table_name='sync_event')
    op.drop_index(op.f('ix_sync_event_device_id'), table_name='sync_event')
    op.drop_table('sync_event')
    op.drop_index(op.f('ix_inventory_movement_tenant_id'), table_name='inventory_movement')
    op.drop_index(op.f('ix_inventory_movement_inventory_item_id'), table_name='inventory_movement')
    op.drop_index(op.f('ix_inventory_movement_farm_id'), table_name='inventory_movement')
    op.drop_table('inventory_movement')
    op.drop_index(op.f('ix_inventory_item_tenant_id'), table_name='inventory_item')
    op.drop_index(op.f('ix_inventory_item_farm_id'), table_name='inventory_item')
    op.drop_table('inventory_item')
    op.drop_index(op.f('ix_field_tenant_id'), table_name='field')
    op.drop_index(op.f('ix_field_farm_id'), table_name='field')
    op.drop_table('field')
    op.drop_index(op.f('ix_animal_tenant_id'), table_name='animal')
    op.drop_index(op.f('ix_animal_farm_id'), table_name='animal')
    op.drop_table('animal')
    # ### end Alembic commands ###

    op.execute("DROP FUNCTION IF EXISTS app_current_tenant_id()")
