"""farmos stage 3: treatments, observations, milk, eggs, harvest, agriculture

Revision ID: de1b1a212f04
Revises: f6f362c79150
Create Date: 2026-08-28 08:44:36.214138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de1b1a212f04'
down_revision: Union[str, None] = 'f6f362c79150'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_RLS_TABLES = [
    "crop",
    "crop_planting",
    "daily_harvest",
    "egg_record",
    "harvest_record",
    "milk_record",
    "observation",
    "treatment",
]


def _enable_rls(table: str) -> None:
    # Mandatory tenant isolation for every new farm-data-plane table — see
    # TENANCY.md and the initial tenant migration, which created
    # app_current_tenant_id().
    op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
    op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
    op.execute(
        f"""
        CREATE POLICY tenant_isolation_{table}
        ON {table}
        USING (tenant_id = app_current_tenant_id())
        WITH CHECK (tenant_id = app_current_tenant_id())
        """
    )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crop',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('default_cycle_days', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('origin_device_id', sa.UUID(), nullable=True),
    sa.Column('last_modified_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crop_farm_id'), 'crop', ['farm_id'], unique=False)
    op.create_index(op.f('ix_crop_tenant_id'), 'crop', ['tenant_id'], unique=False)
    op.create_table('crop_planting',
    sa.Column('field_id', sa.UUID(), nullable=False),
    sa.Column('crop_id', sa.UUID(), nullable=False),
    sa.Column('variety', sa.String(), nullable=True),
    sa.Column('planted_area', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('area_unit', sa.String(length=16), nullable=True),
    sa.Column('planted_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_harvest_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_yield_kg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('origin_device_id', sa.UUID(), nullable=True),
    sa.Column('last_modified_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crop_planting_crop_id'), 'crop_planting', ['crop_id'], unique=False)
    op.create_index(op.f('ix_crop_planting_farm_id'), 'crop_planting', ['farm_id'], unique=False)
    op.create_index(op.f('ix_crop_planting_field_id'), 'crop_planting', ['field_id'], unique=False)
    op.create_index(op.f('ix_crop_planting_tenant_id'), 'crop_planting', ['tenant_id'], unique=False)
    op.create_table('daily_harvest',
    sa.Column('field_id', sa.UUID(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('total_quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sellable_quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('waste_quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('inventory_item_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('origin_device_id', sa.UUID(), nullable=True),
    sa.Column('last_modified_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_harvest_farm_id'), 'daily_harvest', ['farm_id'], unique=False)
    op.create_index(op.f('ix_daily_harvest_field_id'), 'daily_harvest', ['field_id'], unique=False)
    op.create_index(op.f('ix_daily_harvest_tenant_id'), 'daily_harvest', ['tenant_id'], unique=False)
    op.create_table('egg_record',
    sa.Column('flock_id', sa.String(length=64), nullable=False),
    sa.Column('total_eggs', sa.Integer(), nullable=False),
    sa.Column('sellable_eggs', sa.Integer(), nullable=False),
    sa.Column('broken_eggs', sa.Integer(), nullable=False),
    sa.Column('consumed', sa.Integer(), nullable=False),
    sa.Column('hatched', sa.Integer(), nullable=False),
    sa.Column('wasted', sa.Integer(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('origin_device_id', sa.UUID(), nullable=True),
    sa.Column('last_modified_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_egg_record_farm_id'), 'egg_record', ['farm_id'], unique=False)
    op.create_index(op.f('ix_egg_record_tenant_id'), 'egg_record', ['tenant_id'], unique=False)
    op.create_table('harvest_record',
    sa.Column('field_id', sa.UUID(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('waste_qty', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('destination', sa.String(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('origin_device_id', sa.UUID(), nullable=True),
    sa.Column('last_modified_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_harvest_record_farm_id'), 'harvest_record', ['farm_id'], unique=False)
    op.create_index(op.f('ix_harvest_record_field_id'), 'harvest_record', ['field_id'], unique=False)
    op.create_index(op.f('ix_harvest_record_tenant_id'), 'harvest_record', ['tenant_id'], unique=False)
    op.create_table('milk_record',
    sa.Column('animal_id', sa.UUID(), nullable=False),
    sa.Column('session', sa.String(length=16), nullable=False),
    sa.Column('liters', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('quality_status', sa.String(length=32), nullable=False),
    sa.Column('destination', sa.String(length=32), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('origin_device_id', sa.UUID(), nullable=True),
    sa.Column('last_modified_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_milk_record_animal_id'), 'milk_record', ['animal_id'], unique=False)
    op.create_index(op.f('ix_milk_record_farm_id'), 'milk_record', ['farm_id'], unique=False)
    op.create_index(op.f('ix_milk_record_tenant_id'), 'milk_record', ['tenant_id'], unique=False)
    op.create_table('observation',
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('observation_type', sa.String(length=64), nullable=False),
    sa.Column('quality', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('value_numeric', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('value_text', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observer_id', sa.UUID(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('origin_device_id', sa.UUID(), nullable=True),
    sa.Column('last_modified_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observation_farm_id'), 'observation', ['farm_id'], unique=False)
    op.create_index(op.f('ix_observation_tenant_id'), 'observation', ['tenant_id'], unique=False)
    op.create_table('treatment',
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('diagnosis', sa.String(), nullable=True),
    sa.Column('medication', sa.String(), nullable=False),
    sa.Column('dose', sa.String(), nullable=False),
    sa.Column('route', sa.String(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('withdrawal_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('vet_id', sa.UUID(), nullable=True),
    sa.Column('responsible_user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('origin_device_id', sa.UUID(), nullable=True),
    sa.Column('last_modified_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treatment_farm_id'), 'treatment', ['farm_id'], unique=False)
    op.create_index(op.f('ix_treatment_tenant_id'), 'treatment', ['tenant_id'], unique=False)
    for _table in _RLS_TABLES:
        _enable_rls(_table)
    op.add_column('field', sa.Column('crop_type', sa.String(), nullable=True))
    op.add_column('field', sa.Column('area_value', sa.Numeric(precision=10, scale=3), nullable=True))
    op.add_column('field', sa.Column('area_unit', sa.String(length=16), nullable=True))
    op.add_column('field', sa.Column('stage', sa.String(), nullable=True))
    op.add_column('field', sa.Column('expected_harvest_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('field', sa.Column('est_yield_kg', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('field', sa.Column('field_code', sa.String(length=32), nullable=True))
    op.add_column('field', sa.Column('location_label', sa.String(), nullable=True))
    op.add_column('field', sa.Column('soil_type', sa.String(), nullable=True))
    op.add_column('field', sa.Column('irrigation_method', sa.String(), nullable=True))
    op.add_column(
        'field',
        sa.Column('status', sa.String(length=32), nullable=False, server_default='active'),
    )
    op.add_column('field', sa.Column('notes', sa.String(), nullable=True))
    op.drop_column('field', 'area_hectares')
    op.drop_column('field', 'crop')
    op.drop_column('field', 'attributes')
    op.add_column('inventory_item', sa.Column('category', sa.String(), nullable=True))
    op.add_column(
        'inventory_item',
        sa.Column('current_qty', sa.Numeric(precision=14, scale=3), nullable=False, server_default='0'),
    )
    op.add_column(
        'inventory_item',
        sa.Column('reorder_level', sa.Numeric(precision=14, scale=3), nullable=False, server_default='0'),
    )
    op.add_column('inventory_item', sa.Column('supplier_label', sa.String(), nullable=True))
    op.add_column('inventory_item', sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('inventory_item', sa.Column('last_purchase', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('inventory_item', 'quantity_on_hand')
    op.drop_column('inventory_item', 'sku')
    op.add_column('inventory_movement', sa.Column('linked_entity_type', sa.String(), nullable=True))
    op.add_column('inventory_movement', sa.Column('linked_entity_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_movement', 'linked_entity_id')
    op.drop_column('inventory_movement', 'linked_entity_type')
    op.add_column('inventory_item', sa.Column('sku', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.add_column('inventory_item', sa.Column('quantity_on_hand', sa.NUMERIC(precision=14, scale=3), autoincrement=False, nullable=False))
    op.drop_column('inventory_item', 'last_purchase')
    op.drop_column('inventory_item', 'unit_cost')
    op.drop_column('inventory_item', 'supplier_label')
    op.drop_column('inventory_item', 'reorder_level')
    op.drop_column('inventory_item', 'current_qty')
    op.drop_column('inventory_item', 'category')
    op.add_column('field', sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('field', sa.Column('crop', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('field', sa.Column('area_hectares', sa.NUMERIC(precision=10, scale=3), autoincrement=False, nullable=True))
    op.drop_column('field', 'notes')
    op.drop_column('field', 'status')
    op.drop_column('field', 'irrigation_method')
    op.drop_column('field', 'soil_type')
    op.drop_column('field', 'location_label')
    op.drop_column('field', 'field_code')
    op.drop_column('field', 'est_yield_kg')
    op.drop_column('field', 'expected_harvest_date')
    op.drop_column('field', 'stage')
    op.drop_column('field', 'area_unit')
    op.drop_column('field', 'area_value')
    op.drop_column('field', 'crop_type')
    op.drop_index(op.f('ix_treatment_tenant_id'), table_name='treatment')
    op.drop_index(op.f('ix_treatment_farm_id'), table_name='treatment')
    op.drop_table('treatment')
    op.drop_index(op.f('ix_observation_tenant_id'), table_name='observation')
    op.drop_index(op.f('ix_observation_farm_id'), table_name='observation')
    op.drop_table('observation')
    op.drop_index(op.f('ix_milk_record_tenant_id'), table_name='milk_record')
    op.drop_index(op.f('ix_milk_record_farm_id'), table_name='milk_record')
    op.drop_index(op.f('ix_milk_record_animal_id'), table_name='milk_record')
    op.drop_table('milk_record')
    op.drop_index(op.f('ix_harvest_record_tenant_id'), table_name='harvest_record')
    op.drop_index(op.f('ix_harvest_record_field_id'), table_name='harvest_record')
    op.drop_index(op.f('ix_harvest_record_farm_id'), table_name='harvest_record')
    op.drop_table('harvest_record')
    op.drop_index(op.f('ix_egg_record_tenant_id'), table_name='egg_record')
    op.drop_index(op.f('ix_egg_record_farm_id'), table_name='egg_record')
    op.drop_table('egg_record')
    op.drop_index(op.f('ix_daily_harvest_tenant_id'), table_name='daily_harvest')
    op.drop_index(op.f('ix_daily_harvest_field_id'), table_name='daily_harvest')
    op.drop_index(op.f('ix_daily_harvest_farm_id'), table_name='daily_harvest')
    op.drop_table('daily_harvest')
    op.drop_index(op.f('ix_crop_planting_tenant_id'), table_name='crop_planting')
    op.drop_index(op.f('ix_crop_planting_field_id'), table_name='crop_planting')
    op.drop_index(op.f('ix_crop_planting_farm_id'), table_name='crop_planting')
    op.drop_index(op.f('ix_crop_planting_crop_id'), table_name='crop_planting')
    op.drop_table('crop_planting')
    op.drop_index(op.f('ix_crop_tenant_id'), table_name='crop')
    op.drop_index(op.f('ix_crop_farm_id'), table_name='crop')
    op.drop_table('crop')
    # ### end Alembic commands ###
