"""farmos animal/task fields, notification table

Revision ID: f6f362c79150
Revises: cebaa357eecc
Create Date: 2026-08-28 08:18:45.370109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f6f362c79150'
down_revision: Union[str, None] = 'cebaa357eecc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('module_code', sa.String(length=64), nullable=False),
    sa.Column('notification_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('origin_device_id', sa.UUID(), nullable=True),
    sa.Column('last_modified_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_farm_id'), 'notification', ['farm_id'], unique=False)
    op.create_index(op.f('ix_notification_tenant_id'), 'notification', ['tenant_id'], unique=False)

    # Mandatory tenant isolation — see TENANCY.md and the initial tenant
    # migration, which created app_current_tenant_id().
    op.execute("ALTER TABLE notification ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE notification FORCE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY tenant_isolation_notification
        ON notification
        USING (tenant_id = app_current_tenant_id())
        WITH CHECK (tenant_id = app_current_tenant_id())
        """
    )

    op.add_column(
        'animal', sa.Column('tag', sa.String(length=64), nullable=False, server_default='')
    )
    op.add_column('animal', sa.Column('breed', sa.String(), nullable=True))
    op.add_column('animal', sa.Column('sex', sa.String(length=1), nullable=True))
    op.add_column(
        'animal', sa.Column('status', sa.String(length=32), nullable=False, server_default='healthy')
    )
    op.add_column('animal', sa.Column('location_label', sa.String(), nullable=True))
    op.add_column(
        'animal', sa.Column('health_score', sa.Integer(), nullable=False, server_default='100')
    )
    op.add_column(
        'animal', sa.Column('pregnant', sa.Boolean(), nullable=False, server_default=sa.false())
    )
    op.add_column('animal', sa.Column('pregnancy_days', sa.Integer(), nullable=True))
    op.add_column(
        'animal', sa.Column('lactating', sa.Boolean(), nullable=False, server_default=sa.false())
    )
    op.add_column('animal', sa.Column('lactation_cycle', sa.Integer(), nullable=True))
    op.add_column('animal', sa.Column('withdrawal_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('animal', sa.Column('withdrawal_reason', sa.String(), nullable=True))
    op.add_column('animal', sa.Column('weight_kg', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('animal', sa.Column('group_name', sa.String(), nullable=True))
    op.add_column('animal', sa.Column('photo_path', sa.String(), nullable=True))
    op.add_column('animal', sa.Column('acquisition_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('animal', sa.Column('acquisition_source', sa.String(), nullable=True))
    op.add_column('animal', sa.Column('sire_tag', sa.String(), nullable=True))
    op.add_column('animal', sa.Column('dam_tag', sa.String(), nullable=True))
    op.add_column('animal', sa.Column('color_markings', sa.String(), nullable=True))
    op.add_column('animal', sa.Column('purchase_cost', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('animal', sa.Column('current_value', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('animal', sa.Column('notes', sa.String(), nullable=True))
    op.add_column(
        'animal', sa.Column('active', sa.Boolean(), nullable=False, server_default=sa.true())
    )
    op.alter_column('animal', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('animal', 'tag_code')
    op.drop_column('animal', 'attributes')
    op.add_column('task', sa.Column('description', sa.String(), nullable=True))
    op.add_column(
        'task', sa.Column('priority', sa.String(length=16), nullable=False, server_default='medium')
    )
    op.add_column('task', sa.Column('source_type', sa.String(), nullable=True))
    op.add_column('task', sa.Column('source_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'source_id')
    op.drop_column('task', 'source_type')
    op.drop_column('task', 'priority')
    op.drop_column('task', 'description')
    op.add_column('animal', sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('animal', sa.Column('tag_code', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.alter_column('animal', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('animal', 'active')
    op.drop_column('animal', 'notes')
    op.drop_column('animal', 'current_value')
    op.drop_column('animal', 'purchase_cost')
    op.drop_column('animal', 'color_markings')
    op.drop_column('animal', 'dam_tag')
    op.drop_column('animal', 'sire_tag')
    op.drop_column('animal', 'acquisition_source')
    op.drop_column('animal', 'acquisition_date')
    op.drop_column('animal', 'photo_path')
    op.drop_column('animal', 'group_name')
    op.drop_column('animal', 'weight_kg')
    op.drop_column('animal', 'withdrawal_reason')
    op.drop_column('animal', 'withdrawal_until')
    op.drop_column('animal', 'lactation_cycle')
    op.drop_column('animal', 'lactating')
    op.drop_column('animal', 'pregnancy_days')
    op.drop_column('animal', 'pregnant')
    op.drop_column('animal', 'health_score')
    op.drop_column('animal', 'location_label')
    op.drop_column('animal', 'status')
    op.drop_column('animal', 'sex')
    op.drop_column('animal', 'breed')
    op.drop_column('animal', 'tag')
    op.drop_index(op.f('ix_notification_tenant_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_farm_id'), table_name='notification')
    op.drop_table('notification')
    # ### end Alembic commands ###
