"""initial control schema

Revision ID: 17183600cffa
Revises: 
Create Date: 2026-08-27 17:29:57.824278

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '17183600cffa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_flag',
    sa.Column('flag_code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('enabled_globally', sa.Boolean(), nullable=False),
    sa.Column('enabled_tenant_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_flag_flag_code'), 'feature_flag', ['flag_code'], unique=True)
    op.create_table('module_catalog',
    sa.Column('module_code', sa.String(length=64), nullable=False),
    sa.Column('name_en', sa.String(), nullable=False),
    sa.Column('name_ar', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('minimum_app_version', sa.String(), nullable=False),
    sa.Column('dependencies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('default_features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('commercial_status', sa.String(length=16), nullable=False),
    sa.Column('trial_allowed', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('module_code')
    )
    op.create_table('plan',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('limits', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_code'), 'plan', ['code'], unique=True)
    op.create_table('tenant',
    sa.Column('company_code', sa.String(length=32), nullable=False),
    sa.Column('legal_name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('default_currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('ONBOARDING', 'TRIAL', 'ACTIVE', 'GRACE', 'SUSPENDED', 'TERMINATED', name='tenantstatus', native_enum=False, length=64), nullable=False),
    sa.Column('onboarding_status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETE', name='onboardingstatus', native_enum=False, length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_company_code'), 'tenant', ['company_code'], unique=True)
    op.create_table('user_identity',
    sa.Column('idp_subject', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_identity_email'), 'user_identity', ['email'], unique=True)
    op.create_index(op.f('ix_user_identity_idp_subject'), 'user_identity', ['idp_subject'], unique=True)
    op.create_table('audit_event',
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_type', sa.Enum('PLATFORM_USER', 'TENANT_USER', 'DEVICE', 'SYSTEM', name='actortype', native_enum=False, length=64), nullable=False),
    sa.Column('actor_role', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('before_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('correlation_id', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_event_action'), 'audit_event', ['action'], unique=False)
    op.create_index(op.f('ix_audit_event_correlation_id'), 'audit_event', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_event_created_at'), 'audit_event', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_event_tenant_id'), 'audit_event', ['tenant_id'], unique=False)
    op.create_table('backup_job',
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('job_type', sa.Enum('DATABASE_BACKUP', 'TENANT_SNAPSHOT', name='backupjobtype', native_enum=False, length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'EXPIRED', name='jobstatus', native_enum=False, length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('storage_key', sa.String(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backup_job_tenant_id'), 'backup_job', ['tenant_id'], unique=False)
    op.create_table('billing_account',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('billing_email', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_account_tenant_id'), 'billing_account', ['tenant_id'], unique=True)
    op.create_table('farm',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('farm_code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timezone_override', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'farm_code', name='uq_farm_tenant_code')
    )
    op.create_index('ix_farm_tenant_active', 'farm', ['tenant_id', 'active'], unique=False)
    op.create_index(op.f('ix_farm_tenant_id'), 'farm', ['tenant_id'], unique=False)
    op.create_table('file_object',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=True),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum', sa.String(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user_identity.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_file_object_tenant_id'), 'file_object', ['tenant_id'], unique=False)
    op.create_table('plan_module',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('module_code', sa.String(length=64), nullable=False),
    sa.Column('included', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['module_code'], ['module_catalog.module_code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'module_code', name='uq_plan_module')
    )
    op.create_index(op.f('ix_plan_module_plan_id'), 'plan_module', ['plan_id'], unique=False)
    op.create_table('platform_role_assignment',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('platform_role', sa.String(length=64), nullable=False),
    sa.Column('granted_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['granted_by'], ['user_identity.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_identity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'platform_role', name='uq_platform_role_user')
    )
    op.create_index(op.f('ix_platform_role_assignment_user_id'), 'platform_role_assignment', ['user_id'], unique=False)
    op.create_table('subscription',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ONBOARDING_TRIAL', 'ACTIVE', 'GRACE', 'SUSPENDED', 'TERMINATED', name='subscriptionstatus', native_enum=False, length=64), nullable=False),
    sa.Column('billing_cycle', sa.Enum('MONTHLY', 'ANNUAL', name='billingcycle', native_enum=False, length=64), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('renews_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('grace_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_tenant_id'), 'subscription', ['tenant_id'], unique=True)
    op.create_table('support_case',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('opened_by', sa.UUID(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='supportcasestatus', native_enum=False, length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['opened_by'], ['user_identity.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_case_tenant_id'), 'support_case', ['tenant_id'], unique=False)
    op.create_table('tenant_data_locator',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.Enum('SHARED_RLS', 'DEDICATED_DB', name='tenantdatamode', native_enum=False, length=64), nullable=False),
    sa.Column('connection_secret_ref', sa.String(), nullable=True),
    sa.Column('schema_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_table('tenant_entitlement',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('module_code', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('INACTIVE', 'TRIAL', 'ACTIVE', 'SCHEDULED_DISABLE', 'SUSPENDED', 'EXPIRED', name='entitlementstatus', native_enum=False, length=64), nullable=False),
    sa.Column('source', sa.Enum('PLAN', 'OVERRIDE', 'TRIAL', name='entitlementsource', native_enum=False, length=64), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['user_identity.id'], ),
    sa.ForeignKeyConstraint(['module_code'], ['module_catalog.module_code'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'module_code', name='uq_tenant_entitlement')
    )
    op.create_index(op.f('ix_tenant_entitlement_tenant_id'), 'tenant_entitlement', ['tenant_id'], unique=False)
    op.create_table('tenant_export',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'EXPIRED', name='jobstatus', native_enum=False, length=64), nullable=False),
    sa.Column('storage_key', sa.String(), nullable=True),
    sa.Column('download_url_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['requested_by'], ['user_identity.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_export_tenant_id'), 'tenant_export', ['tenant_id'], unique=False)
    op.create_table('usage_meter',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('metric_code', sa.String(length=64), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'metric_code', 'period_start', name='uq_usage_meter_period')
    )
    op.create_index(op.f('ix_usage_meter_tenant_id'), 'usage_meter', ['tenant_id'], unique=False)
    op.create_table('device',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=True),
    sa.Column('installation_id', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('platform', sa.Enum('ANDROID', 'IOS', 'WEB', 'OTHER', name='deviceplatform', native_enum=False, length=64), nullable=False),
    sa.Column('app_version', sa.String(), nullable=False),
    sa.Column('fingerprint_hash', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'REVOKED', 'LOST', 'RETIRED', name='devicestatus', native_enum=False, length=64), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by', sa.UUID(), nullable=True),
    sa.Column('revoked_reason', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['revoked_by'], ['user_identity.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_installation_id'), 'device', ['installation_id'], unique=True)
    op.create_index(op.f('ix_device_tenant_id'), 'device', ['tenant_id'], unique=False)
    op.create_table('invoice',
    sa.Column('billing_account_id', sa.UUID(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ISSUED', 'PAID', 'OVERDUE', 'VOID', name='invoicestatus', native_enum=False, length=64), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['billing_account_id'], ['billing_account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_billing_account_id'), 'invoice', ['billing_account_id'], unique=False)
    op.create_table('subscription_item',
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('item_code', sa.String(length=64), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_item_subscription_id'), 'subscription_item', ['subscription_id'], unique=False)
    op.create_table('support_session',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('support_user_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('scope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['user_identity.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['support_case.id'], ),
    sa.ForeignKeyConstraint(['support_user_id'], ['user_identity.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_session_tenant_id'), 'support_session', ['tenant_id'], unique=False)
    op.create_table('tenant_membership',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='membershipstatus', native_enum=False, length=64), nullable=False),
    sa.Column('tenant_role', sa.Enum('TENANT_OWNER', 'FARM_MANAGER', 'EMPLOYEE', name='tenantrole', native_enum=False, length=64), nullable=False),
    sa.Column('default_farm_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['default_farm_id'], ['farm.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_identity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'user_id', name='uq_membership_tenant_user')
    )
    op.create_index(op.f('ix_tenant_membership_tenant_id'), 'tenant_membership', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tenant_membership_user_id'), 'tenant_membership', ['user_id'], unique=False)
    op.create_table('device_activation',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=True),
    sa.Column('code_hash', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'USED', 'EXPIRED', 'REVOKED', name='deviceactivationstatus', native_enum=False, length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_by_device_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user_identity.id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['used_by_device_id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_activation_code_hash'), 'device_activation', ['code_hash'], unique=True)
    op.create_index(op.f('ix_device_activation_tenant_id'), 'device_activation', ['tenant_id'], unique=False)
    op.create_table('license_lease',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('policy_version', sa.Integer(), nullable=False),
    sa.Column('modules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('farm_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('permission_profile_hash', sa.String(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_license_lease_device_id'), 'license_lease', ['device_id'], unique=False)
    op.create_index(op.f('ix_license_lease_tenant_id'), 'license_lease', ['tenant_id'], unique=False)
    op.create_table('membership_farm_access',
    sa.Column('membership_id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['membership_id'], ['tenant_membership.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('membership_id', 'farm_id', name='uq_membership_farm')
    )
    op.create_index(op.f('ix_membership_farm_access_farm_id'), 'membership_farm_access', ['farm_id'], unique=False)
    op.create_index(op.f('ix_membership_farm_access_membership_id'), 'membership_farm_access', ['membership_id'], unique=False)
    op.create_table('membership_module_permission',
    sa.Column('membership_id', sa.UUID(), nullable=False),
    sa.Column('module_code', sa.String(length=64), nullable=False),
    sa.Column('permission_code', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['membership_id'], ['tenant_membership.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('membership_id', 'module_code', 'permission_code', name='uq_membership_permission')
    )
    op.create_index(op.f('ix_membership_module_permission_membership_id'), 'membership_module_permission', ['membership_id'], unique=False)
    op.create_index(op.f('ix_membership_module_permission_module_code'), 'membership_module_permission', ['module_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_membership_module_permission_module_code'), table_name='membership_module_permission')
    op.drop_index(op.f('ix_membership_module_permission_membership_id'), table_name='membership_module_permission')
    op.drop_table('membership_module_permission')
    op.drop_index(op.f('ix_membership_farm_access_membership_id'), table_name='membership_farm_access')
    op.drop_index(op.f('ix_membership_farm_access_farm_id'), table_name='membership_farm_access')
    op.drop_table('membership_farm_access')
    op.drop_index(op.f('ix_license_lease_tenant_id'), table_name='license_lease')
    op.drop_index(op.f('ix_license_lease_device_id'), table_name='license_lease')
    op.drop_table('license_lease')
    op.drop_index(op.f('ix_device_activation_tenant_id'), table_name='device_activation')
    op.drop_index(op.f('ix_device_activation_code_hash'), table_name='device_activation')
    op.drop_table('device_activation')
    op.drop_index(op.f('ix_tenant_membership_user_id'), table_name='tenant_membership')
    op.drop_index(op.f('ix_tenant_membership_tenant_id'), table_name='tenant_membership')
    op.drop_table('tenant_membership')
    op.drop_index(op.f('ix_support_session_tenant_id'), table_name='support_session')
    op.drop_table('support_session')
    op.drop_index(op.f('ix_subscription_item_subscription_id'), table_name='subscription_item')
    op.drop_table('subscription_item')
    op.drop_index(op.f('ix_invoice_billing_account_id'), table_name='invoice')
    op.drop_table('invoice')
    op.drop_index(op.f('ix_device_tenant_id'), table_name='device')
    op.drop_index(op.f('ix_device_installation_id'), table_name='device')
    op.drop_table('device')
    op.drop_index(op.f('ix_usage_meter_tenant_id'), table_name='usage_meter')
    op.drop_table('usage_meter')
    op.drop_index(op.f('ix_tenant_export_tenant_id'), table_name='tenant_export')
    op.drop_table('tenant_export')
    op.drop_index(op.f('ix_tenant_entitlement_tenant_id'), table_name='tenant_entitlement')
    op.drop_table('tenant_entitlement')
    op.drop_table('tenant_data_locator')
    op.drop_index(op.f('ix_support_case_tenant_id'), table_name='support_case')
    op.drop_table('support_case')
    op.drop_index(op.f('ix_subscription_tenant_id'), table_name='subscription')
    op.drop_table('subscription')
    op.drop_index(op.f('ix_platform_role_assignment_user_id'), table_name='platform_role_assignment')
    op.drop_table('platform_role_assignment')
    op.drop_index(op.f('ix_plan_module_plan_id'), table_name='plan_module')
    op.drop_table('plan_module')
    op.drop_index(op.f('ix_file_object_tenant_id'), table_name='file_object')
    op.drop_table('file_object')
    op.drop_index(op.f('ix_farm_tenant_id'), table_name='farm')
    op.drop_index('ix_farm_tenant_active', table_name='farm')
    op.drop_table('farm')
    op.drop_index(op.f('ix_billing_account_tenant_id'), table_name='billing_account')
    op.drop_table('billing_account')
    op.drop_index(op.f('ix_backup_job_tenant_id'), table_name='backup_job')
    op.drop_table('backup_job')
    op.drop_index(op.f('ix_audit_event_tenant_id'), table_name='audit_event')
    op.drop_index(op.f('ix_audit_event_created_at'), table_name='audit_event')
    op.drop_index(op.f('ix_audit_event_correlation_id'), table_name='audit_event')
    op.drop_index(op.f('ix_audit_event_action'), table_name='audit_event')
    op.drop_table('audit_event')
    op.drop_index(op.f('ix_user_identity_idp_subject'), table_name='user_identity')
    op.drop_index(op.f('ix_user_identity_email'), table_name='user_identity')
    op.drop_table('user_identity')
    op.drop_index(op.f('ix_tenant_company_code'), table_name='tenant')
    op.drop_table('tenant')
    op.drop_index(op.f('ix_plan_code'), table_name='plan')
    op.drop_table('plan')
    op.drop_table('module_catalog')
    op.drop_index(op.f('ix_feature_flag_flag_code'), table_name='feature_flag')
    op.drop_table('feature_flag')
    # ### end Alembic commands ###
