"""farmos tablet contract: employee profile fields, module catalog metadata, entitlement plan caps, idempotency records

Revision ID: 67cdc086039d
Revises: 17183600cffa
Create Date: 2026-08-28 08:07:59.019309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '67cdc086039d'
down_revision: Union[str, None] = '17183600cffa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farmos_idempotency_record',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_identity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', 'user_id', name='uq_idempotency_key_user')
    )
    op.create_index(op.f('ix_farmos_idempotency_record_key'), 'farmos_idempotency_record', ['key'], unique=False)
    op.create_index(op.f('ix_farmos_idempotency_record_user_id'), 'farmos_idempotency_record', ['user_id'], unique=False)
    op.add_column('module_catalog', sa.Column('group', sa.String(), nullable=False, server_default=''))
    op.add_column('module_catalog', sa.Column('license_code', sa.String(), nullable=True))
    op.add_column('tenant', sa.Column('region', sa.String(), nullable=True))
    # Widened from VARCHAR(2): the FarmOS contract's GET /farms/me returns
    # a display value like "Lebanon", not an ISO-2 code.
    op.alter_column('tenant', 'country', type_=sa.String(), existing_type=sa.String(length=2))
    op.add_column('tenant_entitlement', sa.Column('plan', sa.String(), nullable=True))
    op.add_column('tenant_entitlement', sa.Column('max_users', sa.Integer(), nullable=True))
    op.add_column('tenant_entitlement', sa.Column('max_products', sa.Integer(), nullable=True))
    op.add_column(
        'tenant_membership', sa.Column('role', sa.String(), nullable=False, server_default='worker')
    )
    op.add_column('tenant_membership', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('tenant_membership', sa.Column('department', sa.String(), nullable=True))
    op.add_column(
        'tenant_membership', sa.Column('language', sa.String(), nullable=False, server_default='en')
    )
    op.add_column('tenant_membership', sa.Column('job_title', sa.String(), nullable=True))
    op.add_column(
        'tenant_membership',
        sa.Column('employment_status', sa.String(), nullable=False, server_default='active'),
    )
    op.add_column('tenant_membership', sa.Column('start_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tenant_membership', sa.Column('photo_path', sa.String(), nullable=True))
    op.add_column('tenant_membership', sa.Column('working_days', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('tenant_membership', sa.Column('working_hours', sa.String(), nullable=True))
    op.add_column('tenant_membership', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('user_identity', sa.Column('password_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_identity', 'password_hash')
    op.drop_column('tenant_membership', 'notes')
    op.drop_column('tenant_membership', 'working_hours')
    op.drop_column('tenant_membership', 'working_days')
    op.drop_column('tenant_membership', 'photo_path')
    op.drop_column('tenant_membership', 'start_date')
    op.drop_column('tenant_membership', 'employment_status')
    op.drop_column('tenant_membership', 'job_title')
    op.drop_column('tenant_membership', 'language')
    op.drop_column('tenant_membership', 'department')
    op.drop_column('tenant_membership', 'phone')
    op.drop_column('tenant_membership', 'role')
    op.drop_column('tenant_entitlement', 'max_products')
    op.drop_column('tenant_entitlement', 'max_users')
    op.drop_column('tenant_entitlement', 'plan')
    op.alter_column('tenant', 'country', type_=sa.String(length=2), existing_type=sa.String())
    op.drop_column('tenant', 'region')
    op.drop_column('module_catalog', 'license_code')
    op.drop_column('module_catalog', 'group')
    op.drop_index(op.f('ix_farmos_idempotency_record_user_id'), table_name='farmos_idempotency_record')
    op.drop_index(op.f('ix_farmos_idempotency_record_key'), table_name='farmos_idempotency_record')
    op.drop_table('farmos_idempotency_record')
    # ### end Alembic commands ###
