"""farmos audit fields: module_code, summary, changes_json, metadata_json, device

Revision ID: 9cff7b1c5dc1
Revises: 67cdc086039d
Create Date: 2026-08-28 08:56:03.710970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9cff7b1c5dc1'
down_revision: Union[str, None] = '67cdc086039d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_event', sa.Column('module_code', sa.String(), nullable=True))
    op.add_column('audit_event', sa.Column('summary', sa.String(), nullable=True))
    op.add_column('audit_event', sa.Column('changes_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column(
        'audit_event',
        sa.Column(
            'metadata_json',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
    )
    op.add_column('audit_event', sa.Column('device', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_event', 'device')
    op.drop_column('audit_event', 'metadata_json')
    op.drop_column('audit_event', 'changes_json')
    op.drop_column('audit_event', 'summary')
    op.drop_column('audit_event', 'module_code')
    # ### end Alembic commands ###
